apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql
  type: Opaque
  stringData:
    database: heroes-database
    username: superman
    password: superman
